--Insertar en DIRECJAV
INSERT INTO DIRECJAV VALUES (1,'JAVIER LOPEZ','ENCAJERAS 12, Nº 12, 1D','08/11/1995','SI');
INSERT INTO DIRECJAV VALUES (2,'JASON','CARPETANA 13, Nº 22, 1F','01/01/2000','SI');
INSERT INTO DIRECJAV VALUES (3,'MARIO','LIBERTAD 2, Nº 3, 4D','08/11/1985','SI');
INSERT INTO DIRECJAV VALUES (4,'EDUARDO','QUÉ LOCURA 13, Nº 3, 4D','08/11/1963','NO');
INSERT INTO DIRECJAV VALUES (5,'PEDRO','AMAZIN QUICK 3, Nº 3, 4D','23/02/1983','NO');
INSERT INTO DIRECJAV VALUES (6,'Pepito','Haber studiao, Nº 13, 8D','08/04/1993','NO');
INSERT INTO DIRECJAV VALUES (7,'EDUARDO','NEW YORK 7, Nº 4, 2F','08/11/2000','NO');
INSERT INTO DIRECJAV VALUES (8,'ALBERTO','INVENTO 20, Nº 8, 5F','02/6/1998','NO');

--Insertar en ORQUESJAV
INSERT INTO ORQUESJAV VALUES (1,'Los Chamacos','CAOBA 1F','PRIMAVERA',SYSDATE,1,40);
INSERT INTO ORQUESJAV VALUES (2,'Nintenderos Fans','Kasukabe','OTOÑO',SYSDATE,3,23);
INSERT INTO ORQUESJAV VALUES (3,'Tocadores del Cielo','Barcelona','INVIERNO',SYSDATE,1,60);
INSERT INTO ORQUESJAV VALUES (4,'Bacanería','MALLORCA','OTOÑO',SYSDATE,2,60);
INSERT INTO ORQUESJAV VALUES (5,'Confugiradores','Madrid','Verano',SYSDATE,1,100);
INSERT INTO ORQUESJAV VALUES (6,'Locatis','Melilla','PRIMAVERA',SYSDATE,3,20);
INSERT INTO ORQUESJAV VALUES (7,'Veri nice','ANDORRA','PRIMAVERA',SYSDATE,1,80);
INSERT INTO ORQUESJAV VALUES (8,'Linuxwin','Madrid','OTOÑO',SYSDATE,1,200);

--Insertar en CONJAV - CREAR TRIGGER QUE COMPRUEBE SI ES TITULAR - 
INSERT INTO CONJAV VALUES (1,'Zelda requiem',2);
INSERT INTO CONJAV VALUES (2,'Back in York',1);
INSERT INTO CONJAV VALUES (3,'Classic News',3);
INSERT INTO CONJAV VALUES (4,'Locurote',8);
INSERT INTO CONJAV VALUES (5,'Bacanería ambiente',6);
INSERT INTO CONJAV VALUES (6,'Sin parar',4);

--Insertar en DIRRELORQ  - - - * - - -
--INSERT INTO DIRRELORQ VALUES (1,3);
--INSERT INTO DIRRELORQ VALUES (2,1);
--INSERT INTO DIRRELORQ VALUES (3,2);
--INSERT INTO DIRRELORQ VALUES (2,4);
--INSERT INTO DIRRELORQ VALUES (3,6);
--INSERT INTO DIRRELORQ VALUES (1,5);

--Insertar en COMPJAV
INSERT INTO COMPJAV VALUES (1,'Mozart',51,'27/01/1756','05/12/1791');
INSERT INTO COMPJAV VALUES (2,'Beethoven',45,'16/12/1770','26/03/1827');
INSERT INTO COMPJAV VALUES (3,'El Pepe',5,'12/04/1987',null);
INSERT INTO COMPJAV VALUES (4,'Nintendo',300,'12/04/2006',null);
INSERT INTO COMPJAV VALUES (5,'Menol',20,'12/01/1986',null);
INSERT INTO COMPJAV VALUES (6,'Javiel',30,'01/05/1990',null);
INSERT INTO COMPJAV VALUES (7,'Uematsu',20,'12/04/1980',null);

--Insertar en OBRAJAV
INSERT INTO OBRAJAV VALUES (1,'Allegro',1);
INSERT INTO OBRAJAV VALUES (2,'Menuetto y Trio',1);
INSERT INTO OBRAJAV VALUES (3,'La bemol mayor',2);
INSERT INTO OBRAJAV VALUES (4,'Romanza',2);
INSERT INTO OBRAJAV VALUES (5,'La bacanería',3);
INSERT INTO OBRAJAV VALUES (6,'BacanYork',3);
INSERT INTO OBRAJAV VALUES (7,'Menol klk',3);
INSERT INTO OBRAJAV VALUES (8,'Aria Song',4);

--Insertar en CONRELOBRA
INSERT INTO CONRELOBRA VALUES (3,2);
INSERT INTO CONRELOBRA VALUES (3,3);
INSERT INTO CONRELOBRA VALUES (2,6);
INSERT INTO CONRELOBRA VALUES (1,8);
INSERT INTO CONRELOBRA VALUES (2,7);
INSERT INTO CONRELOBRA VALUES (4,3);
INSERT INTO CONRELOBRA VALUES (5,5);
INSERT INTO CONRELOBRA VALUES (6,5);

--Insertar en SOLIJAV
INSERT INTO SOLIJAV VALUES (1,'El Tartas','03/05/1990','Violín');
INSERT INTO SOLIJAV VALUES (2,'Federico','20/02/1983','Tambor');
INSERT INTO SOLIJAV VALUES (3,'Antonio','09/11/1975','Violín');
INSERT INTO SOLIJAV VALUES (4,'Javiel','01/01/2001','Trombón');
INSERT INTO SOLIJAV VALUES (5,'Ivan','09/11/2000','Guitarra');
INSERT INTO SOLIJAV VALUES (6,'Danieh','01/12/2000','Triángulo');
INSERT INTO SOLIJAV VALUES (7,'Miguelico','09/11/1988','Bajo');
INSERT INTO SOLIJAV VALUES (8,'Raul','09/11/1990','Garbanzo');
INSERT INTO SOLIJAV VALUES (9,'Carlos','09/11/1990','Guitarra');
INSERT INTO SOLIJAV VALUES (10,'Ayoub','09/11/2000','Arpa');
INSERT INTO SOLIJAV VALUES (11,'Federico','09/09/9999','Poronga');

--Insertar en OBRARELSOL
INSERT INTO OBRARELSOL VALUES (1,1);
INSERT INTO OBRARELSOL VALUES (2,1);
INSERT INTO OBRARELSOL VALUES (3,2);
INSERT INTO OBRARELSOL VALUES (4,3);
INSERT INTO OBRARELSOL VALUES (5,4);
INSERT INTO OBRARELSOL VALUES (6,5);
INSERT INTO OBRARELSOL VALUES (7,6);
INSERT INTO OBRARELSOL VALUES (8,7);
INSERT INTO OBRARELSOL VALUES (8,10);
INSERT INTO OBRARELSOL VALUES (6,11);


--Insertar en CONRELSOL
INSERT INTO CONRELSOL VALUES (1,1);
INSERT INTO CONRELSOL VALUES (2,2);
INSERT INTO CONRELSOL VALUES (3,2);
INSERT INTO CONRELSOL VALUES (4,3);
INSERT INTO CONRELSOL VALUES (5,4);
INSERT INTO CONRELSOL VALUES (6,4);
INSERT INTO CONRELSOL VALUES (6,5);
INSERT INTO CONRELSOL VALUES (5,10);